version: '3'
services:
  elk:
    container_name: srv-elk
    image: sebp/elk
    networks: 
      - net-elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
networks:
  net-elk: