version: '3'
services:
  web:
    container_name: srv-apache
    image: jorarmarfin/apache-php:7.2
    volumes:
      - ./apache/html:/var/www/html
    ports:
      - 83:80
    restart: always
    networks:
      - net-elastic
  db:
    container_name: srv-mysql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    restart: always
    networks:
      - net-elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: srv-elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - net-elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: srv-kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://srv-elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - net-elastic
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    container_name: srv-logstash
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - net-elastic
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      #- ./logstash/config/:/usr/share/logstash/config/
networks:
  net-elastic:
volumes:
  elastic-data: