version: '3'
services:
  elk:
    container_name: srv-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    networks: 
      - net-elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
networks:
  net-elk:

