version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: srv-elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - net-elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: srv-kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://srv-elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - net-elastic
networks:
  net-elastic:
volumes:
  elastic-data: